name: Wake Streamlit App (Hard Reset)
on:
  schedule:
    - cron: '0 0 * * *' # Runs once a day at midnight
  workflow_dispatch:      # Allows manual trigger

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Make empty commit
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git commit --allow-empty -m "Scheduled keep-alive commit"
          git push
